#!/usr/bin/env ruby

# Crude script to pretty print XML from standard input to standard output

require 'rexml/document'

doc = REXML::Document.new($stdin)
formatter = REXML::Formatters::Pretty.new
formatter.compact = true
formatter.write(doc, $stdout)
puts
